### ISSUE TITLE
Incorporate in our BPMN test model several "service task" using for each one a different available implementation type.

### ISSUE THREAD

**Issue by olvegam** [BPMN-sw-evol/MSGF-BPM-Engine#21]
For solving this issue, we must: 

1. Search examples of use for each implementation type. We can start doing it in the Cammunda 7 documentation and next in Camunda Forum. 

2. Once we have this knowledge we can propose an use in our BPMN test model example.    

NOTE: This issue was assigned to de MSGF-BPM-Engine repo because there we must deploy our modified BPMN model.

**Comment by danilonunezgil** [comment]
Only these implementation types:

- External
- Expression
- Connector

NOTE: Start by researching on Camunda forums or similar sites what they are used for.
